version: "3.9"

networks:
  app-network-2-test:

services:
  pg_db-2-test:
    image: postgres:15.1
    container_name: pg_name-2-test
    restart: always
    environment:
      POSTGRES_DB: "postgres_test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pg_data"
    volumes:
      - ./extension.sql:/docker-entrypoint-initdb.d/extension.sql
    ports:
      - "54321:5432"
    networks:
      - app-network-2-test

  cache-redis-test:
    image: redis:7.0.7-alpine
    restart: always
    ports:
      - '63791:6379'
    command: redis-server --port 63791 --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - app-network-2-test
  app-test:
    build:
      context: .
    depends_on:
      - pg_db-2-test
      - cache-redis-test
    container_name: app-backend-2-test
    command: sh -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0"
    volumes:
      - ./app:/app
    ports:
      - "9000:8000"
    tty: true
    stdin_open: true
    restart: always
    networks:
      - app-network-2-test
    environment:
      DB_URL: "postgresql+asyncpg://postgres:postgres@pg_db-2-test/postgres_test?prepared_statement_cache_size=0"
      PORT: 9000
      PYTHONPATH: "/app"
      DEBUG: "0"
      REDIS_HOST: cache-redis-test
      REDIS_PORT: 63791
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
